apiVersion: apps/v1
kind: ReplicaSet
metadata:
        name: prod
spec:
        replicas: 3
        selector:
                matchLabels:
                        app: myapp
        template:
                metadata:
                        labels:
                                app: myapp
                spec:
                        containers:
                                - name: cont3
                                  image: httpd
