apiVersion: apps/v1
kind: ReplicaSet
metadata:
        name: sales-app
spec:
        replicas: 2
        selector:
                matchLabels:
                        app: sales
        template:
                metadata:
                        labels:
                                app: sales
                spec:
                        containers:
                                - name: cont2
                                  image: nginx
